//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-22 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16793601L
#error FIX8_SERUM_Trade_session.hpp version 1.4.1 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// FIX8_SERUM_Trade_session.hpp
//-------------------------------------------------------------------------------------------------
#ifndef FIX8_464958385F534552554D5F54726164655F73657373696F6E2E687070_
#define FIX8_464958385F534552554D5F54726164655F73657373696F6E2E687070_

//-------------------------------------------------------------------------------------------------
// server session and router classes
//-------------------------------------------------------------------------------------------------
class FIX8_SERUM_Trade_session_server;

class FIX8_SERUM_Trade_router_server : public FIX8::SERUM_Trade::FIX8_SERUM_Trade_Router
{
   FIX8_SERUM_Trade_session_server& _session; 

public:
   FIX8_SERUM_Trade_router_server(FIX8_SERUM_Trade_session_server& session) : _session(session) {}
   virtual ~FIX8_SERUM_Trade_router_server() {}

   // Override these methods to receive specific message callbacks.
   // bool operator() (const FIX8::SERUM_Trade::Heartbeat *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TestRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ResendRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Reject *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SequenceReset *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Logout *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::IOI *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Advertisement *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ExecutionReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderCancelReject *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Logon *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::DerivativeSecurityList *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::NewOrderMultileg *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MultilegOrderCancelReplace *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TradeCaptureReportRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TradeCaptureReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderMassStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::QuoteRequestReject *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::RFQRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::QuoteStatusReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::QuoteResponse *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Confirmation *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::PositionMaintenanceRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::PositionMaintenanceReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::RequestForPositions *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::RequestForPositionsAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::PositionReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TradeCaptureReportRequestAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TradeCaptureReportAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::AllocationReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::AllocationReportAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ConfirmationAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SettlementInstructionRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::AssignmentReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CollateralRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CollateralAssignment *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CollateralResponse *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::News *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CollateralReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CollateralInquiry *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::NetworkCounterpartySystemStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::NetworkCounterpartySystemStatusResponse *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::UserRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::UserResponse *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CollateralInquiryAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ConfirmationRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Email *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::NewOrderSingle *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::NewOrderList *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderCancelRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderCancelReplaceRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::AllocationInstruction *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ListCancelRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ListExecute *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ListStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ListStatus *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::AllocationInstructionAck *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::DontKnowTrade *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::QuoteRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::Quote *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SettlementInstructions *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MarketDataRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MarketDataSnapshotFullRefresh *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MarketDataIncrementalRefresh *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MarketDataRequestReject *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::QuoteCancel *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::QuoteStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MassQuoteAcknowledgement *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityDefinitionRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityDefinition *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityStatus *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TradingSessionStatusRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::TradingSessionStatus *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::MassQuote *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::BusinessMessageReject *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::BidRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::BidResponse *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::ListStrikePrice *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::XMLnonFIX *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::RegistrationInstructions *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::RegistrationInstructionsResponse *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderMassCancelRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::OrderMassCancelReport *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::NewOrderCross *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CrossOrderCancelReplaceRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::CrossOrderCancelRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityTypeRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityTypes *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityListRequest *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::SecurityList *msg) const;
   // bool operator() (const FIX8::SERUM_Trade::DerivativeSecurityListRequest *msg) const;
};

//-------------------------------------------------------------------------------------------------
class FIX8_SERUM_Trade_session_server : public FIX8::Session
{
   FIX8_SERUM_Trade_router_server _router; 

public:
   FIX8_SERUM_Trade_session_server(const FIX8::F8MetaCntx& ctx, FIX8::Persister *persist=0,
      FIX8::Logger *logger=0, FIX8::Logger *plogger=0) : Session(ctx, persist, logger, plogger), _router(*this) {} 

   // Override these methods if required but remember to call the base class method first.
   // bool handle_logon(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_logon(const unsigned heartbeat_interval, const f8String davi=f8String());
   // bool handle_logout(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_logout();
   // bool handle_heartbeat(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_heartbeat(const f8String& testReqID);
   // bool handle_resend_request(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_resend_request(const unsigned begin, const unsigned end=0);
   // bool handle_sequence_reset(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_sequence_reset(const unsigned newseqnum, const bool gapfillflag=false);
   // bool handle_test_request(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_test_request(const f8String& testReqID);
   // bool handle_reject(const unsigned seqnum, const FIX8::Message *msg);
   // Message *generate_reject(const unsigned seqnum, const char *what);
   // bool handle_admin(const unsigned seqnum, const FIX8::Message *msg);
   // void modify_outbound(FIX8::Message *msg);
   // bool authenticate(SessionID& id, const FIX8::Message *msg);

   // Override these methods to intercept admin and application methods.
   // bool handle_admin(const unsigned seqnum, const FIX8::Message *msg);

   bool handle_application(const unsigned seqnum, const FIX8::Message *&msg);
   /* In your compilation unit, this should be implemented with something like the following:
   bool FIX8_SERUM_Trade_session_server::handle_application(const unsigned seqnum, const FIX8::Message *&msg)
   {
      return enforce(seqnum, msg) || msg->process(_router);
   }
   */
};

#endif // FIX8_464958385F534552554D5F54726164655F73657373696F6E2E687070_
